In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('silver.csv')

df[:5]

    latitude  longitude   depth   mag          id  hour        date
0  34.189835 -117.58800   6.000  1.70  ci12317071     0  1973-01-01
1  -9.214000  150.63400  41.000  5.30  usp0000001     3  1973-01-01
2  48.308666 -122.11733  13.680  2.20  uw10840118     4  1973-01-01
3 -15.012000 -173.95800  33.000  5.00  usp0000002     5  1973-01-01
4  19.443666 -155.36084   7.302  1.85  hv19723167     7  1973-01-01

### Covert date

In [3]:
df['date'] = pd.to_datetime(df['date'])

### Magnitude analysis

In [4]:
df['mag_rounded_down'] = df['mag'].astype(int)

df.groupby('mag_rounded_down').agg({'id': 'count'})

                       id
mag_rounded_down
-9                    706
-5                      1
-2                     11
-1                   2389
 0                 994070
 1                1550998
 2                 642669
 3                 211629
 4                 372804
 5                  73634
 6                   6135
 7                    634
 8                     37
 9                      2

### Calculate energy

In [5]:
df['energy'] = 5.24
df['energy'] += 1.44 * df['mag']
df['energy'] = np.power(10, df['energy'])

### Count through years

In [9]:
plt.hist(df['date'], bins = 500);

TypeError: boxplot() got an unexpected keyword argument 'bins'